<?php
/**
 * Body24
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * Body24 Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Body24 implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'body_24';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'attribute_set_id' => 'int',
        'attribute_group_id' => 'int',
        'attribute_code' => 'string',
        'sort_order' => 'int'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'attribute_set_id' => 'attributeSetId',
        'attribute_group_id' => 'attributeGroupId',
        'attribute_code' => 'attributeCode',
        'sort_order' => 'sortOrder'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'attribute_set_id' => 'setAttributeSetId',
        'attribute_group_id' => 'setAttributeGroupId',
        'attribute_code' => 'setAttributeCode',
        'sort_order' => 'setSortOrder'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'attribute_set_id' => 'getAttributeSetId',
        'attribute_group_id' => 'getAttributeGroupId',
        'attribute_code' => 'getAttributeCode',
        'sort_order' => 'getSortOrder'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['attribute_set_id'] = isset($data['attribute_set_id']) ? $data['attribute_set_id'] : null;
        $this->container['attribute_group_id'] = isset($data['attribute_group_id']) ? $data['attribute_group_id'] : null;
        $this->container['attribute_code'] = isset($data['attribute_code']) ? $data['attribute_code'] : null;
        $this->container['sort_order'] = isset($data['sort_order']) ? $data['sort_order'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['attribute_set_id'] === null) {
            $invalid_properties[] = "'attribute_set_id' can't be null";
        }
        if ($this->container['attribute_group_id'] === null) {
            $invalid_properties[] = "'attribute_group_id' can't be null";
        }
        if ($this->container['attribute_code'] === null) {
            $invalid_properties[] = "'attribute_code' can't be null";
        }
        if ($this->container['sort_order'] === null) {
            $invalid_properties[] = "'sort_order' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['attribute_set_id'] === null) {
            return false;
        }
        if ($this->container['attribute_group_id'] === null) {
            return false;
        }
        if ($this->container['attribute_code'] === null) {
            return false;
        }
        if ($this->container['sort_order'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets attribute_set_id
     * @return int
     */
    public function getAttributeSetId()
    {
        return $this->container['attribute_set_id'];
    }

    /**
     * Sets attribute_set_id
     * @param int $attribute_set_id
     * @return $this
     */
    public function setAttributeSetId($attribute_set_id)
    {
        $this->container['attribute_set_id'] = $attribute_set_id;

        return $this;
    }

    /**
     * Gets attribute_group_id
     * @return int
     */
    public function getAttributeGroupId()
    {
        return $this->container['attribute_group_id'];
    }

    /**
     * Sets attribute_group_id
     * @param int $attribute_group_id
     * @return $this
     */
    public function setAttributeGroupId($attribute_group_id)
    {
        $this->container['attribute_group_id'] = $attribute_group_id;

        return $this;
    }

    /**
     * Gets attribute_code
     * @return string
     */
    public function getAttributeCode()
    {
        return $this->container['attribute_code'];
    }

    /**
     * Sets attribute_code
     * @param string $attribute_code
     * @return $this
     */
    public function setAttributeCode($attribute_code)
    {
        $this->container['attribute_code'] = $attribute_code;

        return $this;
    }

    /**
     * Gets sort_order
     * @return int
     */
    public function getSortOrder()
    {
        return $this->container['sort_order'];
    }

    /**
     * Sets sort_order
     * @param int $sort_order
     * @return $this
     */
    public function setSortOrder($sort_order)
    {
        $this->container['sort_order'] = $sort_order;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


