<?php
/**
 * CatalogInventoryStockStatusCriteriaInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CatalogInventoryStockStatusCriteriaInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface StockStatusCriteriaInterface
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CatalogInventoryStockStatusCriteriaInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CatalogInventoryStockStatusCriteriaInterface"
     */
    public function testCatalogInventoryStockStatusCriteriaInterface()
    {

    }

    /**
     * Test attribute "mapper_interface_name"
     */
    public function testPropertyMapperInterfaceName()
    {

    }

    /**
     * Test attribute "criteria_list"
     */
    public function testPropertyCriteriaList()
    {

    }

    /**
     * Test attribute "filters"
     */
    public function testPropertyFilters()
    {

    }

    /**
     * Test attribute "orders"
     */
    public function testPropertyOrders()
    {

    }

    /**
     * Test attribute "limit"
     */
    public function testPropertyLimit()
    {

    }

}
