<?php
/**
 * ConfigurableProductDataOptionInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ConfigurableProductDataOptionInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface OptionInterface
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConfigurableProductDataOptionInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ConfigurableProductDataOptionInterface"
     */
    public function testConfigurableProductDataOptionInterface()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "attribute_id"
     */
    public function testPropertyAttributeId()
    {

    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {

    }

    /**
     * Test attribute "position"
     */
    public function testPropertyPosition()
    {

    }

    /**
     * Test attribute "is_use_default"
     */
    public function testPropertyIsUseDefault()
    {

    }

    /**
     * Test attribute "values"
     */
    public function testPropertyValues()
    {

    }

    /**
     * Test attribute "extension_attributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {

    }

}
