<?php
/**
 * SalesDataShipmentTrackInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SalesDataShipmentTrackInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Shipment track interface. A shipment is a delivery package that contains products. A shipment document accompanies the shipment. This document lists the products and their quantities in the delivery package. Merchants and customers can track shipments.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SalesDataShipmentTrackInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SalesDataShipmentTrackInterface"
     */
    public function testSalesDataShipmentTrackInterface()
    {

    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {

    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {

    }

    /**
     * Test attribute "entity_id"
     */
    public function testPropertyEntityId()
    {

    }

    /**
     * Test attribute "parent_id"
     */
    public function testPropertyParentId()
    {

    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {

    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {

    }

    /**
     * Test attribute "qty"
     */
    public function testPropertyQty()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "extension_attributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

    /**
     * Test attribute "track_number"
     */
    public function testPropertyTrackNumber()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "carrier_code"
     */
    public function testPropertyCarrierCode()
    {

    }

}
