<?php
/**
 * SalesDataCreditmemoCreationArgumentsInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SalesDataCreditmemoCreationArgumentsInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface CreditmemoCreationArgumentsInterface
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SalesDataCreditmemoCreationArgumentsInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SalesDataCreditmemoCreationArgumentsInterface"
     */
    public function testSalesDataCreditmemoCreationArgumentsInterface()
    {

    }

    /**
     * Test attribute "shipping_amount"
     */
    public function testPropertyShippingAmount()
    {

    }

    /**
     * Test attribute "adjustment_positive"
     */
    public function testPropertyAdjustmentPositive()
    {

    }

    /**
     * Test attribute "adjustment_negative"
     */
    public function testPropertyAdjustmentNegative()
    {

    }

    /**
     * Test attribute "extension_attributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

}
