<?php
/**
 * SalesRuleDataConditionInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SalesRuleDataConditionInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface ConditionInterface
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SalesRuleDataConditionInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SalesRuleDataConditionInterface"
     */
    public function testSalesRuleDataConditionInterface()
    {

    }

    /**
     * Test attribute "condition_type"
     */
    public function testPropertyConditionType()
    {

    }

    /**
     * Test attribute "conditions"
     */
    public function testPropertyConditions()
    {

    }

    /**
     * Test attribute "aggregator_type"
     */
    public function testPropertyAggregatorType()
    {

    }

    /**
     * Test attribute "operator"
     */
    public function testPropertyOperator()
    {

    }

    /**
     * Test attribute "attribute_name"
     */
    public function testPropertyAttributeName()
    {

    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {

    }

    /**
     * Test attribute "extension_attributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

}
