<?php
/**
 * CustomerCustomerRepositoryV1ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CustomerCustomerRepositoryV1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomerCustomerRepositoryV1ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for customerCustomerRepositoryV1DeleteByIdDelete
     *
     * .
     *
     */
    public function testCustomerCustomerRepositoryV1DeleteByIdDelete()
    {

    }

    /**
     * Test case for customerCustomerRepositoryV1GetByIdGet
     *
     * .
     *
     */
    public function testCustomerCustomerRepositoryV1GetByIdGet()
    {

    }

    /**
     * Test case for customerCustomerRepositoryV1GetByIdGet_0
     *
     * .
     *
     */
    public function testCustomerCustomerRepositoryV1GetByIdGet0()
    {

    }

    /**
     * Test case for customerCustomerRepositoryV1GetListGet
     *
     * .
     *
     */
    public function testCustomerCustomerRepositoryV1GetListGet()
    {

    }

    /**
     * Test case for customerCustomerRepositoryV1SavePut
     *
     * .
     *
     */
    public function testCustomerCustomerRepositoryV1SavePut()
    {

    }

    /**
     * Test case for customerCustomerRepositoryV1SavePut_0
     *
     * .
     *
     */
    public function testCustomerCustomerRepositoryV1SavePut0()
    {

    }

}
