<?php
/**
 * QuoteCartManagementV1ApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * QuoteCartManagementV1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QuoteCartManagementV1ApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for quoteCartManagementV1AssignCustomerPut
     *
     * .
     *
     */
    public function testQuoteCartManagementV1AssignCustomerPut()
    {

    }

    /**
     * Test case for quoteCartManagementV1CreateEmptyCartForCustomerPost
     *
     * .
     *
     */
    public function testQuoteCartManagementV1CreateEmptyCartForCustomerPost()
    {

    }

    /**
     * Test case for quoteCartManagementV1CreateEmptyCartForCustomerPost_0
     *
     * .
     *
     */
    public function testQuoteCartManagementV1CreateEmptyCartForCustomerPost0()
    {

    }

    /**
     * Test case for quoteCartManagementV1CreateEmptyCartPost
     *
     * .
     *
     */
    public function testQuoteCartManagementV1CreateEmptyCartPost()
    {

    }

    /**
     * Test case for quoteCartManagementV1GetCartForCustomerGet
     *
     * .
     *
     */
    public function testQuoteCartManagementV1GetCartForCustomerGet()
    {

    }

    /**
     * Test case for quoteCartManagementV1PlaceOrderPut
     *
     * .
     *
     */
    public function testQuoteCartManagementV1PlaceOrderPut()
    {

    }

    /**
     * Test case for quoteCartManagementV1PlaceOrderPut_0
     *
     * .
     *
     */
    public function testQuoteCartManagementV1PlaceOrderPut0()
    {

    }

}
